name: remote ssh command
on: 
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: dev
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
              bench init --frappe-branch version-13 frappe-bench
              cd frappe-bench
              
